# Generated by Django 5.2.1 on 2025-05-18 18:28

import django.db.models.deletion
import fl_platform.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fl_platform', '0002_remove_traininggroup_model_architecture_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientUpdateSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weights_file', models.FileField(upload_to=fl_platform.models.client_update_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending_aggregation', max_length=20)),
                ('global_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_updates', to='fl_platform.globalmodel')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('training_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_submissions', to='fl_platform.traininggroup')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
